name: multi jobs
on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Excecute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAW" >> dragon.txt
              
            - name: upload dragon artifact 
              uses: actions/upload-artifact@v4
              with:
                name: muti-job-artifact
                path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: download dragon artifact 
              uses: actions/download-artifact@v4
              with:
                name: muti-job-artifact

            - name: Test file exists
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: download artifact 
              uses: actions/download-artifact@v4
              with:
               name: muti-job-artifact

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo deploying...